Vagrant.configure("2") do |config|

  config.vm.define "hub" do |hub|
    hub.vm.box = "ubuntu/precise64"
    hub.vm.box_url = "http://files.vagrantup.com/precise64.box"
    hub.vm.network "private_network", ip: "192.168.10.2"
    hub.vm.network "forwarded_port", guest: 4444, host: 4444
    hub.vm.provision "shell", path: "hub/provision.sh"
  end

  config.vm.define "node-ubuntu-firefox" do |node|
    node.vm.box = "ubuntu/precise64"
    node.vm.box_url = "http://files.vagrantup.com/precise64.box"
    node.vm.network "private_network", ip: "192.168.10.3"
    node.vm.provision "shell", path: "node-ubuntu-firefox/provision.sh"
  end

  config.vm.define "node-ubuntu-chrome" do |node|
    node.vm.box = "ubuntu/precise64"
    node.vm.box_url = "http://files.vagrantup.com/precise64.box"
    node.vm.network "private_network", ip: "192.168.10.4"
    node.vm.provision "shell", path: "node-ubuntu-chrome/provision.sh"
  end

  config.vm.define "node-win8-ie10" do |node|
    node.vm.box = "win8-ie10"
    node.vm.box_url = "http://aka.ms/vagrant-win8-ie10"
    node.vm.communicator = "winrm"
    node.vm.network "private_network", ip: "192.168.10.5"

    node.vm.provider "virtualbox" do |v|
      v.gui = true
    end
  end

  config.vm.define "node-win81-ie11" do |node|
    node.vm.box = "win81-ie11"
    node.vm.box_url = "http://aka.ms/vagrant-win81-ie11"
    node.vm.communicator = "winrm"
    node.vm.network "private_network", ip: "192.168.10.6"

    node.vm.provider "virtualbox" do |v|
      v.gui = true
    end
  end

end
