Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  config.vm.network "private_network", ip: "192.168.50.5"
  config.vm.provision "shell", path: "provision.sh"
end
