@startuml

actor "Test Script"
participant Datepicker
participant Calendar
participant Trigger

activate "Test Script"
activate Browser

"Test Script" -> Datepicker : pick(APRIL, 1, 2018)
activate Datepicker
Datepicker -> Calendar : show()
activate Calendar
Calendar -> Trigger: accept(browser)
activate Trigger
Trigger -> Browser: click(DATE_FIELD)
Browser -> Browser: diaplay the calendar

deactivate Trigger
deactivate Calendar
deactivate Datepicker

deactivate "Test Script"

@enduml