@startuml

actor "Test Script"
participant Datepicker
participant Calendar
participant YearPicker
participant MonthPicker
participant DayPicker

activate "Test Script"


"Test Script" -> Datepicker : pick(APRIL, 1, 2018)
activate Datepicker
Datepicker -> Calendar : show()
activate Calendar

deactivate Calendar
Datepicker -> YearPicker: pickYear(2018)
activate YearPicker
deactivate YearPicker

Datepicker -> MonthPicker: pickMonth(APRIL)
activate MonthPicker
deactivate MonthPicker


Datepicker -> DayPicker: pickDay(1)
activate DayPicker
deactivate DayPicker

deactivate Datepicker

deactivate "Test Script"

@enduml